// GET Products API
export const GET_PRODUCTS_API = 'GET_PRODUCTS_API';
export const GET_PRODUCTS_API_LOADING = 'GET_PRODUCTS_API_LOADING';

// ADD_PRODUCT API
export const ADD_PRODUCT_API = 'ADD_PRODUCT_API';

// UPDATE_PRODUCT API
export const UPDATE_PRODUCT_API = 'UPDATE_PRODUCT_API';

// DELETE_PRODUCT API
export const DELETE_PRODUCT_API = 'DELETE_PRODUCT_API';
